import type { Metadata } from 'next';
import { Figtree } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import Navigation from './navigation';
import { ThemeProvider } from '@/components/theme-provider';

const figtree = Figtree({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en'>
            <body
                className={cn(
                    'bg-background font-sans text-[0.900rem]/[1.35rem] antialiased',
                    figtree.variable,
                )}>
                <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
                    <Navigation />
                    <div className='mt-[5.5rem] bg-transparent' />
                    <div className='mx-auto h-[1000rem] min-h-screen max-w-screen-2xl'>
                        <main>{children}</main>
                    </div>
                </ThemeProvider>
            </body>
        </html>
    );
}
